CREATE TABLE `flow_today` (
  `keyid` int(10) unsigned NOT NULL COMMENT 'Key ID',
  `ip_s` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'IP Source Address',
  `ip_d` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'IP Destination Address',
  `protocol` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'IP Protocol - see table protocols',
  `port_s` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'Port Source',
  `port_d` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'Port Destination',
  `createtime` datetime(6) DEFAULT NULL,
  `starttime` datetime(6) DEFAULT NULL,
  `endtime` datetime(6) DEFAULT NULL,
  `trans` int(10) unsigned NOT NULL DEFAULT '0',
  `bytes` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'Bytes in this flow',
  `packets` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Packets in this flow',
  `retrans` int(10) unsigned NOT NULL DEFAULT '0',
  `jitter_s` float(9,4) unsigned NOT NULL DEFAULT '0.0000',
  `jitter_d` float(9,4) unsigned NOT NULL DEFAULT '0.0000',
  `tcpflags` char(8) DEFAULT '' COMMENT 'TCP Flags',
  `dom_s` int(10) unsigned DEFAULT NULL COMMENT 'Domain (Institution) ID Source',
  `dom_d` int(10) unsigned DEFAULT NULL COMMENT 'Domain (Institution) ID Destination',
  `cc_s` char(2) DEFAULT NULL COMMENT 'Country Code Source',
  `cc_d` char(2) DEFAULT NULL COMMENT 'Country Code Destination',
  `as_s` int(10) unsigned DEFAULT NULL,
  `as_d` int(10) unsigned DEFAULT NULL,
  `router` char(2) DEFAULT '',
  `appid` smallint(5) unsigned DEFAULT NULL COMMENT 'Application ID - i.e., HTTP, Skype, FTP, etc. - see apps table',
  `direction` char(1) DEFAULT '?',
  `mac_s` smallint(5) unsigned NOT NULL DEFAULT '0',
  `mac_d` smallint(5) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`keyid`),
  KEY `ip_s` (`ip_s`),
  KEY `ip_d` (`ip_d`),
  KEY `starttime` (`starttime`),
  KEY `createtime` (`createtime`),
  KEY `dom_s` (`dom_s`),
  KEY `dom_d` (`dom_d`)
) ENGINE=MyISAM AUTO_INCREMENT=15689068 DEFAULT CHARSET=latin1;
